runtests:
	cd exercise-db-1-v1 && go clean -testcache && go test . && grader-cli submit && cd ..
	cd exercise-db-2-v1 && go clean -testcache && go test .  && grader-cli submit && cd ..
	cd exercise-db-3-v1 && go clean -testcache && go test .  && grader-cli submit && cd ..
	cd exercise-db-4-insert-v1 && go clean -testcache && go test .  && grader-cli submit && cd ..
	cd exercise-db-5-update-v1 && go clean -testcache && go test .  && grader-cli submit && cd ..
	cd exercise-db-6-delete-v1 && go clean -testcache && go test .  && grader-cli submit && cd ..
	cd exercise-db-7-query-v1 && go clean -testcache && go test .  && grader-cli submit && cd ..
	cd exercise-db-8-query-v1 && go clean -testcache && go test .  && grader-cli submit && cd ..
	cd exercise-db-9-join-v1 && go clean -testcache && go test .  && grader-cli submit && cd ..
	cd assignment-db-1-v1 && go clean -testcache && go test .  && grader-cli submit && cd ..
	cd assignment-db-2-v1 && go clean -testcache && go test .  && grader-cli submit && cd ..
	cd assignment-db-3-v1 && go clean -testcache && go test .  && grader-cli submit && cd ..
	cd assignment-db-4-join-v1 && go clean -testcache && go test .  && grader-cli submit && cd ..
	cd crud-orm-cp-v1 && go clean -testcache && go test .  && grader-cli submit && cd ..
	cd join-orm-cp-v1 && go clean -testcache && go test .  && grader-cli submit && cd ..
	cd todo-app-with-orm-v1 && go clean -testcache && go test .  && grader-cli submit && cd ..
